# Generated by Django 2.2.5 on 2019-09-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('adress', models.CharField(max_length=200)),
                ('card_number', models.IntegerField()),
                ('identification', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('social_account', models.CharField(max_length=255)),
            ],
        ),
    ]
