# Generated by Django 2.2.6 on 2019-11-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
