# Generated by Django 2.2.6 on 2019-11-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_auto_20191127_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_date',
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
