# Generated by Django 2.2.6 on 2019-12-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_auto_20191129_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='budget',
            field=models.IntegerField(default=0),
        ),
    ]
