# Generated by Django 2.2.5 on 2019-10-01 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('goods_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_app.MyUser'),
            preserve_default=False,
        ),
    ]
