# Generated by Django 2.2.6 on 2019-11-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0005_auto_20191101_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='pictures',
            field=models.ImageField(upload_to='goods_image'),
        ),
    ]
