# Generated by Django 2.2.6 on 2019-11-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0006_auto_20191105_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='pictures',
            new_name='image',
        ),
    ]
