# Generated by Django 2.2.6 on 2019-11-06 13:46

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0008_remove_goods_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos'),
        ),
    ]
