# Generated by Django 2.2.6 on 2019-11-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0009_goods_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
