# Generated by Django 2.2.6 on 2019-12-03 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0014_auto_20191203_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='offer_person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='goods_offer_person', to='user_app.MyUser'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='goods_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
