# Generated by Django 2.2.6 on 2019-12-05 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0015_auto_20191203_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='color',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='size',
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.Category'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
