# Generated by Django 2.2.6 on 2019-12-05 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0016_auto_20191205_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='category',
        ),
        migrations.AlterField(
            model_name='goods',
            name='offer_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_offer_person', to='user_app.MyUser'),
        ),
    ]
