# Generated by Django 2.2.6 on 2019-12-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0017_auto_20191205_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Some',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='auctionDeadLine',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='offer_person',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='owner',
        ),
    ]
